# Generated by Django 3.1.4 on 2021-01-19 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('banda', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guitarra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=50)),
                ('cuerdas', models.IntegerField()),
                ('madera', models.CharField(default='No definida', max_length=50)),
                ('fecha_compra', models.DateField()),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.musico')),
            ],
        ),
    ]
