# Generated by Django 3.1.5 on 2021-01-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_auto_20210120_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='musicos',
            field=models.ManyToManyField(related_name='bandas', to='formularios.Musico'),
        ),
    ]
