# Generated by Django 3.1.4 on 2021-02-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_guitarracbv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guitarracbv',
            options={'ordering': ['id']},
        ),
    ]
